[FileDialog]
history=file:///home/unklebonehead/ReaperProjects, file:///home/unklebonehead/ReaperProjects/Call of the Raven, file:///home/unklebonehead/ReaperProjects/HammerOnDown2022, file:///home/unklebonehead/Music/StickUpBoys, file:///home/unklebonehead/dwhelper, file:///home/unklebonehead/dwhelper/New2
lastVisited=file:///home/unklebonehead/dwhelper/New2
qtVersion=5.15.3
shortcuts=file:, file:///home/unklebonehead
sidebarWidth=96
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xeb\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\b\0\0\0\x1\0\0\0\0\0\0\0;\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0h\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
