#! /bin/sh

bspc rule -r "*"
xrandr --output DisplayPort-0 --mode 1920x1080 --pos 0x0 --rotate normal --output DVI-D-0 --mode 1920x1080 --pos 1920x0 --rotate normal

bspc monitor DisplayPort-0 -d 1 2 3 4 5
# bspc monitor HDMI-A-0 -d 4 5 6 7
bspc monitor DVI-D-0 -d 6 7 8 9 10

bspc config border_width			4
bspc config window_gap				10

bspc config split_ratio				0.5
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config focus_follows_pointer	true

bspc config presel_feedback_color "#56949f"
bspc config active_border_color		"#FFFFFF"
bspc config focused_border_color "#F0C674"
bspc config normal_border_color "#FFFFFF"

bspc rule -a \* rectangle 800x450+0+0 center=true
bspc rule -a qimgv state=floating
bspc rule -a sxiv state=floating
bspc rule -a Xarchiver state=floating layer=normal
bspc rule -a mpv state=floating layer=normal
bspc rule -a Pavucontrol:pavucontrol state=floating
bspc rule -a Lxappearance state=floating layer=normal
bspc rule -a Galculator state=floating layer=normal
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a obs desktop='^10' follow=on
#bspc rule -a Pulsar desktop='^4' follow=on

xsetroot -cursor_name left_ptr
xset s off -dpms
dunst &
picom --config ~/.config/picom/picom.conf &
flatpak run com.github.debauchee.barrier &

## Favorite backgrounds.
#feh --bg-fill ~/.config/backgrounds/deer-forest-outdoor-art.jpg &
feh --bg-fill ~/.config/backgrounds/wallhaven-kw5yy7_3440x1440.png &
#feh --bg-fill ~/.config/backgrounds/wallhaven-85erok_3440x1440.png &
#feh --bg-scale --no-xinerama ~/.config/backgrounds/17.png

## Polybar or tint
~/.config/polybar/launch.sh

## Clipmemu start
# clipmenud &

## apps for systray if enabled
volumeicon &
nm-applet &
sxhkd &
mpd ~/.config/mpd/mpd.conf &
pgrep bspswallow || bspswallow &
